Fixed path in PhantomJS driver, added validate step in build script

diff --git a/bin/wappalyzer-build b/bin/wappalyzer-build
--- a/bin/wappalyzer-build
+++ b/bin/wappalyzer-build
@@ -7,6 +7,15 @@ then
 	exit 1
 fi
 
+wappalyzer validate
+
+if [ $? -ne 0 ]
+then
+	echo "Build aborted"
+
+	exit 1
+fi
+
 wappalyzer links
 
 # Mozilla Firefox
